version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: metadata_editor
    ports:
      - "0.0.0.0:8384:80"
    volumes:
      - ./editor:/var/www/html/editor
      
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: metadataeditor_docker
      DB_USERNAME: metadataeditor_user
      DB_PASSWORD: metadataeditor_password      
  mysql:
      image: mysql:5.7
      container_name: mysql-57-metadata-editor
      restart: always
      ports:
        - 13307:3306
      environment:
        MYSQL_DATABASE: metadataeditor_docker
        MYSQL_USER: metadataeditor_user
        MYSQL_PASSWORD: metadataeditor_password
        MYSQL_ROOT_PASSWORD: root